name: Xinference CD for DockerHub
'on':
  schedule:
  - cron: 0 18 * * *
  push:
    tags:
    - '*'
  workflow_dispatch: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    timeout-minutes: 240
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      shell: bash
      if: ${{ github.repository == 'xorbitsai/inference' }}
      env:
        DOCKER_ORG: ${{ secrets.DOCKERHUB_USERNAME }}
        PY_VERSION: ${{ matrix.python-version }}
      run: "if [[ \"$GITHUB_REF\" =~ ^\"refs/tags/\" ]]; then\n  export GIT_TAG=$(echo\
        \ \"$GITHUB_REF\" | sed -e \"s/refs\\/tags\\///g\")\nfi\n\ndocker system prune\
        \ -f -a\n\nif [[ -n \"$GIT_TAG\" ]]; then\n  BRANCHES=\"$GIT_TAG\"\n  echo\
        \ \"Will handle tag $BRANCHES\"\nelse\n  MAINBRANCH=$(git rev-parse --abbrev-ref\
        \ HEAD)\n  BRANCHES=\"$MAINBRANCH\"\nfi\n\nfor branch in $BRANCHES; do\n \
        \ if [[ -n \"$GIT_TAG\" ]]; then\n    export IMAGE_TAG=\"$GIT_TAG\"\n  else\n\
        \    git checkout $branch\n    export IMAGE_TAG=\"nightly-$branch\"\n  fi\n\
        \  docker build -t \"$DOCKER_ORG/xinference:${IMAGE_TAG}\" --progress=plain\
        \ -f xinference/deploy/docker/Dockerfile .\n  docker push \"$DOCKER_ORG/xinference:${IMAGE_TAG}\"\
        \n  docker build -t \"$DOCKER_ORG/xinference:${IMAGE_TAG}-cpu\" --progress=plain\
        \ -f xinference/deploy/docker/Dockerfile.cpu .\n  docker push \"$DOCKER_ORG/xinference:${IMAGE_TAG}-cpu\"\
        \n  docker build -t \"$DOCKER_ORG/xinference:${IMAGE_TAG}-cu128\" --progress=plain\
        \ -f xinference/deploy/docker/Dockerfile.cu128 .\n  docker push \"$DOCKER_ORG/xinference:${IMAGE_TAG}-cu128\"\
        \n  echo \"XINFERENCE_IMAGE_TAG=${IMAGE_TAG}\" >> $GITHUB_ENV\ndone\n\nif\
        \ [[ -n \"$GIT_TAG\" ]]; then\n  docker tag \"$DOCKER_ORG/xinference:${GIT_TAG}\"\
        \ \"$DOCKER_ORG/xinference:latest\"\n  docker push \"$DOCKER_ORG/xinference:latest\"\
        \n  docker tag \"$DOCKER_ORG/xinference:${GIT_TAG}-cpu\" \"$DOCKER_ORG/xinference:latest-cpu\"\
        \n  docker push \"$DOCKER_ORG/xinference:latest-cpu\"\n  docker tag \"$DOCKER_ORG/xinference:${GIT_TAG}-cu128\"\
        \ \"$DOCKER_ORG/xinference:latest-cu128\"\n  docker push \"$DOCKER_ORG/xinference:latest-cu128\"\
        \n  echo \"XINFERENCE_GIT_TAG=${GIT_TAG}\" >> $GITHUB_ENV\nfi\n"
    - name: Clean docker image cache
      shell: bash
      if: ${{ github.repository == 'xorbitsai/inference' }}
      run: 'docker system prune -f -a

        '
